version: '3.4'

services:
  mangaviewerts:
    image: mangaviewerts
    build:
      context: backend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3050:3050
      - 9229:9229
    command: ["ts-node", "--inspect=0.0.0.0:9228", "src/index.ts"]
